baseURL                          = "https://roxedus.dev/"  # Your domain name. Must end with "/"
theme                            = "introduction"
title = "Roxedus.dev"
DefaultContentLanguage           = "en"                    # Default language for multilingual sites
# disqusshortname                 = ""                       # https://gohugo.io/content-management/comments
# googleAnalytics                 = ""                       # https://gohugo.io/templates/internal/#google-analytics

[params]
    themeStyle                   = "dark"                 # Choose "light" or "dark"
#    favicon                      = "/img/fav.ico"          # Path to favicon file
    showRSSButton                = true                   # Show rss button in navigation
    fadeIn                       = true                    # Turn on/off the fade-in effect
    fadeInIndex                  = false                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "Jan 2, 2006"
    email                        = "me@roxedus.dev"   # E-mail address for contact section
    # customCSS                    = ["foo.css"]             # Include custom css files placed under assets/

    # Configure the home page
    [params.home]
        introHeight              = "medium"            # Input either "medium" or "large" or "fullheight"
        showLatest               = true                    # Show latest blog post summary
        showAllPosts             = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        numberOfProjectsToShow   = 3                       # Maximum number of projects to show on home page. Unset or comment out to show all projects

        localTime                = true                    # Show your current local time in contact section
        timeZone                 = "Europe/Oslo"   # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        timeFormat               = "HH:mm"                # https://momentjs.com/docs/#/displaying/format/
    [params.projects]
        useTwoColumns            = false                   # Use a layout with two columns instead of three

    # Share buttons on blog post pages
    [params.share]
        twitter                  = true

    # Social icons appear in introduction and contact section. Add as many more as you like.
    # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
    # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
    [[params.social]]
        url   = "https://twitter.com/Roxedus"
        icon  = "twitter" # icon name without the 'fa-'
        icon_pack = "fab"

# We only use tag as a taxonomies
# You can add more by yourself
[taxonomies]
  tag = "tags"

[languages]
    [languages.en]
        languageName     = "English"
        languageCode     = "en-us"
        contentDir       = "content/en"
        weight           = 0
        title            = "roxedus.dev"
        [languages.en.params]
            description  = "roxedus.dev"   # Max 160 characters show in search results
            footerText   = " "                      # Text to override default footer text (markdown allowed)