baseURL: https://roxedus.dev

module:
  imports:
  - path: github.com/hugo-toha/toha/v4
  mounts:
  - source: static/files
    target: static/files
  - source: ./node_modules/flag-icon-css/flags
    target: static/flags
  - source: ./node_modules/@fontsource/mulish/files
    target: static/files
  - source: ./node_modules/katex/dist/fonts
    target: static/fonts

defaultContentLanguage: en
languages:
  en:
    languageName: English
    weight: 1
    title: "Simen's Page"
  "no":
    languageName: Norsk
    weight: 2
    title: "Simens side"

# Control TOC depth
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

outputs:
  home:
    - HTML
    - JSON

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # GitHub repo URL of your site
  gitRepo: https://github.com/Roxedus/Roxedus
  gitBranch: main

  background: "images/background.jpg"

  logo:
    main: images/animoji.png
    inverted: images/animoji_transp.png
    favicon: images/animoji.png

  features:
    notes:
      enable: true
    blog:
      enable: false
    darkMode:
      enable: true
    portfolio:
      enable: true
    toc:
      enable: true
    comment:
      enable: false
    videoPlayer:
      enable: false
    analytics:
      enabled: true
    flags:
      enable: true