name: Deploy to Github Pages
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    paths:
      - "site/**"
      - ".github/workflows/deploy-hugo.yml"
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          repository: Roxedus/Talks
          path: upstream_talks
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@2752ce1d29631191ea3f27c23495fa06139a5b78 # v3.2.1
        id: install
        with:
          hugo-version: "0.161.1"
          extended: true
      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24.18.0
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4
      - name: Get certificates
        working-directory: site
        run: |
          ./.get-certs.sh
      - name: Prep hugo
        working-directory: site
        run: |
          hugo mod get
          hugo mod npm pack
          npm install
      - name: Build
        run: hugo -s ./site --minify
      # - name: Talks
      #   run: mkdir ./site/public/talks
      # - name: Build Docker talk files
      #   working-directory: upstream_talks
      #   run: just static docker
      # - name: Move Docker talk
      #   run: mv upstream_talks/docker/_site site/public/talks/docker
      - name: Deploy
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site/public
          cname: roxedus.dev
