name: Test build
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    paths:
      - "site/**"
      - ".github/workflows/deploy-hugo.yml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@2752ce1d29631191ea3f27c23495fa06139a5b78 # v3.2.1
        id: install
        with:
          hugo-version: "0.161.1"
          extended: true
      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        id: setup-node
        with:
          node-version: 24.15.0
      - name: Prep hugo
        working-directory: site
        run: |
          hugo mod get
          hugo mod npm pack
          npm install
      - name: Build
        run: hugo -s ./site --minify
