name: Test build
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    paths:
      - "site/**"
      - ".github/workflows/deploy-hugo.yml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@2752ce1d29631191ea3f27c23495fa06139a5b78 # v3.2.1
        id: install
        with:
          hugo-version: "0.161.1"
          extended: true
      - name: Setup Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        id: setup-node
        with:
          node-version: 24.19.0
      - name: Prep hugo
        working-directory: site
        run: |
          hugo mod get
          hugo mod npm pack
          npm install
      - name: Build
        run: hugo -s ./site --minify
